name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libsystemc libsystemc-dev
    - name: Test
      run: |
        g++ -o hello -std=c++11 -lsystemc src/hello/hello.cpp
        chmod +x hello
        ./hello

